version: '3'

services: 
  web: 
      container_name: mfncompose
      image: nginx:latest
      ports:
      - 80:80
      volumes:
      - ./www:/usr/share/www/html
  php:
      container_name: mfnphp
      image: php:7.2-apache
      depends_on:
      - web
      ports:
      - 8888:80
      volumes:
      - web:/var/www/html
  db:
      container_name: mfdcdb
      image: mysql
      command: --default-authentication-plugin=mysql_native_password
      environment:
       MYSQL_ROOT_PASSWORD: test1234
       MYSQL_USER: usrtest
       MYSQL_DATABASE: test_db
      ports:
      - 6000:3306
volumes:
   web:

